stages:
  - ci
  - publish

default:
  before_script:
    - dotnet tool install --global Cake.Tool --version 0.38.1
    - export PATH="$PATH:/root/.dotnet/tools"

ci:
  stage: ci
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet-cake --bootstrap
    - dotnet-cake
  artifacts:
    reports:
      junit: out/test-results/*.xml
    paths:
      - artifacts/
    expire_in: 60 min

prerelease:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet-cake --bootstrap
    - dotnet-cake -Target=Publish -BuildType=prerelease
  dependencies:
    - ci
  artifacts:
    paths:
      - artifacts/
    expire_in: 60 min
  when: manual
  only:
    - master

release:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet-cake --bootstrap
    - dotnet-cake -Target=Publish -BuildType=release
  dependencies:
    - ci
  artifacts:
    paths:
      - artifacts/
    expire_in: 60 min
  when: manual
  only:
    - master
