stages:
  - build

cake_build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  before_script:
    - dotnet tool install --global Cake.Tool --version 0.33.0
  script:
    - $HOME/.dotnet/tools/dotnet-cake
  artifacts:
    expire_in: 60 min