stages:
  - ci
  - publish

ci:
  stage: ci
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  before_script:
    - dotnet tool install --global Cake.Tool --version 0.33.0
  script:
    - $HOME/.dotnet/tools/dotnet-cake
  artifacts:
    paths:
        - artifacts/
    expire_in: 60 min

prerelease:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  before_script:
    - dotnet tool install --global Cake.Tool --version 0.33.0
  script:
    - $HOME/.dotnet/tools/dotnet-cake -Target=Publish -BuildType=prerelease
  dependencies:
    - ci
  environment:
    name: production
  when: manual
  only:
    - master

release:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  before_script:
    - dotnet tool install --global Cake.Tool --version 0.33.0
  script:
    - $HOME/.dotnet/tools/dotnet-cake -Target=Publish -BuildType=release
  dependencies:
    - ci
  environment:
    name: production
  when: manual
  only:
    - master
