image:
  - Visual Studio 2019
build_script:
  - ps: .\build.ps1 --bootstrap; .\build.ps1
after_build:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "opencovercoverage.xml"