using System.ComponentModel;

namespace DiabloSharp.Models
{
    public enum HeroStatIdentifier
    {
        [Description("life")]
        Life,
        [Description("damage")]
        Damage,
        [Description("toughness")]
        Toughness,
        [Description("healing")]
        Healing,
        [Description("attackSpeed")]
        AttackSpeed,
        [Description("armor")]
        Armor,
        [Description("strength")]
        Strength,
        [Description("dexterity")]
        Dexterity,
        [Description("vitality")]
        Vitality,
        [Description("intelligence")]
        Intelligence,
        [Description("physicalResist")]
        PhysicalResist,
        [Description("fireResist")]
        FireResist,
        [Description("coldResist")]
        ColdResist,
        [Description("lightningResist")]
        LightningResist,
        [Description("poisonResist")]
        PoisonResist,
        [Description("arcaneResist")]
        ArcaneResist,
        [Description("blockChance")]
        BlockChance,
        [Description("blockAmountMin")]
        BlockAmountMin,
        [Description("blockAmountMax")]
        BlockAmountMax,
        [Description("goldFind")]
        GoldFind,
        [Description("critChance")]
        CritChance,
        [Description("thorns")]
        Thorns,
        [Description("lifeSteal")]
        LifeSteal,
        [Description("lifePerKill")]
        LifePerKill,
        [Description("lifeOnHit")]
        LifeOnHit,
        [Description("primaryResource")]
        PrimaryResource,
        [Description("secondaryResource")]
        SecondaryResource
    }
}